"""Add Submission table

Revision ID: 73b3047dfcb7
Revises: 4ff52066c094
Create Date: 2025-02-20 05:45:19.214442

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '73b3047dfcb7'
down_revision = '4ff52066c094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
